# Generated by Django 3.0.3 on 2020-02-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bee_robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(default=0)),
                ('nectar', models.IntegerField(default=0)),
                ('honey', models.IntegerField(default=0)),
                ('fuel', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('speed', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('elevation', models.FloatField(default=0.0)),
            ],
        ),
    ]
