# Generated by Django 3.0.3 on 2020-02-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bee_robot',
            name='id_number',
        ),
    ]
