# Generated by Django 3.0.3 on 2020-02-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bee', '0002_remove_bee_robot_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bee_robot',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
