# Generated by Django 3.0.3 on 2020-02-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bee', '0003_bee_robot_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bee_robot',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
